build.gradle, src/main/java/spot/spot/global/config/GlobalResponseHandler.java, src/main/java/spot/spot/global/controller/HealthCheckController.java, src/main/java/spot/spot/global/dto/response/ResultResponse.java, src/main/java/spot/spot/global/exception/ErrorCode.java, src/main/java/spot/spot/global/exception/GlobalException.java, src/main/java/spot/spot/global/exception/GlobalExceptionHandler.java, src/main/resources/application.properties, src/main/resources/application.yml
- #1 
로직 보시고, 가독성 잡을 부분이나, 이해 안되는 부분 가감 없이 말씀해 주세요!
내부 오류는 원래 보이면 안되는데 개발하는 기간 동안만 API 반환값에 넣겠습니다.
String의 경우 커스텀 예외로 막아두었습니다.
=> FEAT: 공통 응답 및 Error 반환 로직 완성

build.gradle, src/main/java/spot/spot/global/healthCheck/HealthCheckController.java, src/main/resources/application.yml, src/main/resources/logback.xml
- resolved #18
나중에 보고 싶은 로그는 log.warn( ) 이나 error.( ) 로 확인해보시면 될 것 같습니다.
=> chore: make Logging colorful

build.gradle
- resloved #21 
**Map Struct**는 Entity -> DTO, DTO -> Entity를 Mapping 해주는 라이브러리 입니다. 
[사용법 참고](https://medium.com/naver-cloud-platform/%EA%B8%B0%EC%88%A0-%EC%BB%A8%ED%85%90%EC%B8%A0-%EB%AC%B8%EC%9E%90-%EC%95%8C%EB%A6%BC-%EB%B0%9C%EC%86%A1-%EC%84%9C%EB%B9%84%EC%8A%A4-sens%EC%9D%98-mapstruct-%EC%A0%81%EC%9A%A9%EA%B8%B0-8fd2bc2bc33b)
=> chore: MapStruct 환경 구성

src/main/java/spot/spot/global/response/handler/GlobalVaultResponseKeys.java, src/main/resources/application-local.yml, src/main/resources/application.yml
- #50 
사용법은 
GlobalVaultResponseKeys handler;
Map<String, String> vaultKeys = handler.getVaultKeys();
valutKeys.get("key값") 을 넣으시면 value가 반환됩니다.
=> feat: vault key,value 값 반환 map 저장

build.gradle, src/main/java/spot/spot/domain/member/OAuth2FailureHandler.java, src/main/java/spot/spot/domain/member/OAuthProvider.java, src/main/java/spot/spot/domain/member/entity/Member.java, src/main/java/spot/spot/domain/member/entity/OAuth2Member.java, src/main/java/spot/spot/domain/member/entity/dto/MemberRequest.java, src/main/java/spot/spot/domain/member/entity/dto/MemberRole.java, src/main/java/spot/spot/domain/member/entity/dto/OAuth2MemberResponse.java, src/main/java/spot/spot/domain/member/entity/jwt/JwtFilter.java, src/main/java/spot/spot/domain/member/entity/jwt/JwtUtil.java, src/main/java/spot/spot/domain/member/entity/jwt/Token.java, src/main/java/spot/spot/domain/member/repository/MemberRepository.java, src/main/java/spot/spot/domain/member/service/MemberService.java, src/main/java/spot/spot/domain/member/service/OAuth2FailureHandler.java, src/main/java/spot/spot/domain/member/service/OAuth2MemberService.java, src/main/java/spot/spot/domain/member/service/OAuth2SuccessHandler.java, src/main/java/spot/spot/domain/member/service/TokenService.java, src/main/java/spot/spot/global/config/RedisConfig.java, src/main/java/spot/spot/global/config/SecurityConfig.java, src/main/java/spot/spot/global/config/SwaggerConfig.java, src/main/resources/application.yml
- #32 
- 단순히 카카오 로그인과 jwt토큰을 redis에 저장하는 로직만 있습니다. 추후에 로그인 유저 데이터 변경이나, 중복 로그인 토큰 처리는 추가할 예정입니다.
- swagger 접속 url 앞단에 /api 추가했습니다.
=> feat: 카카오 간편 로그인 구현

src/main/java/spot/spot/domain/member/entity/Member.java, src/main/java/spot/spot/domain/member/entity/dto/MemberRequest.java, src/main/java/spot/spot/domain/member/service/OAuth2MemberService.java, src/main/java/spot/spot/global/config/TestDataInitializerConfig.java, src/main/resources/application-dev.yml
디비 테이블 생성 방식을 카멜케이스에서 스네이크케이스 방식으로 변경하였습니다.
=> refactor: dev 디비 엔터티 생성방식 변경

src/main/java/spot/spot/domain/job/_docs/Job4ClientDocs.java, src/main/java/spot/spot/domain/job/_docs/Job4WorkerDocs.java, src/main/java/spot/spot/domain/job/controller/Job4ClientController.java, src/main/java/spot/spot/domain/job/controller/Job4WorkerController.java, src/main/java/spot/spot/domain/job/dto/request/Job4ClientRequest.java, src/main/java/spot/spot/domain/job/dto/request/Job4WorkerRequest.java, src/main/java/spot/spot/domain/job/service/Job4ClientService.java, src/main/java/spot/spot/domain/job/service/Job4WorkerService.java, src/main/java/spot/spot/domain/notification/service/FcmUtil.java
=> FEAT: 의뢰인이 마음에 드는 해결사에게 일을 의뢰하기 API + 의뢰할 시 해결사에게 FCM 알림 보내기

src/main/java/spot/spot/domain/job/_docs/Job4ClientDocs.java, src/main/java/spot/spot/domain/job/_docs/Job4WorkerDocs.java, src/main/java/spot/spot/domain/job/controller/Job4ClientController.java, src/main/java/spot/spot/domain/job/controller/Job4WorkerController.java, src/main/java/spot/spot/domain/job/dto/request/Job2ClientRequest.java, src/main/java/spot/spot/domain/job/dto/request/Job2WorkerRequest.java, src/main/java/spot/spot/domain/job/dto/request/YesOrNo2ClientsRequest.java, src/main/java/spot/spot/domain/job/dto/request/YesOrNo2WorkersRequest.java, src/main/java/spot/spot/domain/job/dto/request/YesOrNoOfClientRequest.java, src/main/java/spot/spot/domain/job/service/Job4ClientService.java, src/main/java/spot/spot/domain/job/service/Job4WorkerService.java, src/main/java/spot/spot/domain/notification/service/FcmUtil.java, src/main/java/spot/spot/global/response/handler/GlobalExceptionHandler.java
=> FEAT: 의뢰자 입장에서 해결사가 잠수 탄 것 같을 때, 위탁 철회 요청을 보내는 API 구현 완료 

src/main/java/spot/spot/domain/job/_docs/Job4ClientDocs.java, src/main/java/spot/spot/domain/job/controller/Job4ClientController.java, src/main/java/spot/spot/domain/job/repository/dsl/ChangeJobStatusDsl.java, src/main/java/spot/spot/domain/job/service/Job4ClientService.java, src/main/java/spot/spot/domain/job/service/Job4WorkerService.java, src/main/java/spot/spot/domain/job/service/JobUtil.java, src/main/java/spot/spot/global/response/format/ErrorCode.java, src/main/java/spot/spot/global/scheduler/SchedulingConfig.java, src/main/java/spot/spot/global/scheduler/SchedulingTask.java
- resolved close #90 
비동기 스케줄링의 과정을 한 번 보시고 자신의 코드가 들어가야할 부분을 생각해보고, 코드 같이 수정해봐요^^
그러면 Main Thread에서 취소 예약을 `ThreadPoolSchedulingExecutor` 와 `ConcurrentHashMap`에 저장
우선순위 큐는 TimeStamp가 가까운 순으로 값을 정렬시키기 때문에 실행 되어야 할 시간이 임박할수록 큐의 front로 오게됨.
이후 빈 백그라운드 스레드에서 일 실행
취소 철회 요청이 들어온 matching-id로 일을 찾고, 해당 일을 Map에서 지움 (Map은 취소 예약된 일을 추적하기 위한 용도) 
우리는 찾은 ConcurrentHashMap을 우선순위 큐에서도 삭제 (우선순위 큐 전체를 돌아야 해서 최악의 시간복잡도 O(N)이 든다.)
취소 예약 밀어넣기 전에 혹시 현재 삭제예약이 걸려 있는지 확인 합니다.
위와 같이 진행되었습니다.
혹시 본인 도메인에서 쓰셔야할 부분이나, 로직적으로 수정해야할 부분이 있으면 이야기 해주시요. 같이 토의해봐요^^
테스트는 취소 예약을 1분으로 걸어놓고 해보았습니다.
저번 PR에서의 조치로 SLEEP 상태였던 5번 유저를 취소시켰습니다.
=> FEAT: 노쇼한 해결사 일 철회 시키기 (의뢰자가 철회 요청 -> 10분 간 해결사에게서 아무 응답이 없으면 취소) 

src/main/java/spot/spot/domain/job/_docs/Job4ClientDocs.java, src/main/java/spot/spot/domain/job/controller/Job4ClientController.java, src/main/java/spot/spot/domain/job/dto/response/JobResponse.java, src/main/java/spot/spot/domain/job/dto/response/JobSituationResponse.java, src/main/java/spot/spot/domain/job/mapper/Job4ClientMapper.java, src/main/java/spot/spot/domain/job/mapper/Job4WorkerMapper.java, src/main/java/spot/spot/domain/job/repository/dsl/SearchingListDsl.java, src/main/java/spot/spot/domain/job/service/Job4ClientService.java, src/main/java/spot/spot/global/response/handler/GlobalExceptionHandler.java, src/main/java/spot/spot/global/response/handler/GlobalResponseHandler.java
- close #91 
- fix #83 
일 하나 확인하기랑 일 실시간 상세 페이지랑 내용이 같은데, API를 굳이 두 개 둘 필요가 없을 것 같아서, 일 실시간 상세 페이지용 API 지웁니다.
일 하나 상세 메타 데이터가 필요할 경우 
- #83
을 활용하시기 바랍니다. 
단순한 삭제 PR이라 스크린샷 생략
=> FIX: 일 처리 실시간 확인 페이지 -> 일 하나 확인하기로 API 통일

src/main/java/spot/spot/domain/pay/entity/PayHistory.java, src/main/java/spot/spot/domain/pay/entity/dto/response/PayReadyResponseDto.java, src/main/java/spot/spot/domain/pay/service/PayService.java
- #159 
불필요한 job update 쿼리가 나가서 matchings의 lazyLoading에서 문제가 발생하여 필드를 삭제하였습니다.
=> fix: payReadyResponseDto payHistory 필드 삭제

src/main/java/spot/spot/domain/job/dto/response/JobDetailResponse.java, src/main/java/spot/spot/domain/job/repository/dsl/MatchingDsl.java, src/main/java/spot/spot/domain/job/service/Job4WorkerService.java, src/main/java/spot/spot/global/response/handler/GlobalResponseHandler.java
- close #163 
- fix #83
> 응답 예시
```java
{
"status": "success",
"message": "정상적으로 처리하였습니다.",
"data": {
"id": 1,
"title": "친절한 고객 응대",
"contnent": "신속한 작업 가능",
"picture": "https://soomin-bucket-1.s3.ap-northeast-2.amazonaws.com/8cabb38110a0aa75bb570f93d8868264_w.jpeg",
"lat": 37.398485,
"lng": 127.113047,
"money": 140081,
"tid": null,
"clientId": 453,
"nickname": "박예준",
"clientImg": "https://ap-northeast-2.console.aws.amazon.com/s3/object/soomin-bucket-1?region=ap-northeast-2&bucketType=general&prefix=basic_user_img.gif",
"myStatus": "YES"
}
}
```
=> FIX: 자신이 신청한 일인지 아닌지 같이 넣기

src/main/java/spot/spot/domain/pay/entity/PayHistory.java
- #183 
데이터 삽입하다가 job과 payHistory가 일대일이 아닌 다대일매핑이 맞아서 수정했습니다.
=> fix: pay_history의 job을 일대일에서 다대일로 수정

src/main/java/spot/spot/domain/notification/query/repository/SearchingNotificationListDsl.java
- fix: #203 
record는 생성자 이용 못함 따라서, 필드 주입식으로 변경.
record는 불변 객체라서 암시적인 생성자만 있을 뿐 명시적 생성자가 없다고 함. 더 알아볼 시간이 없어서 급한대로 field 주입식 QueryDsl로 전환
=> FIX: NOTIFICATION 알림 리스트 Type-case 오류 해결

src/main/java/spot/spot/domain/job/query/controller/_docs/WorkerQueryDocs.java, src/main/java/spot/spot/domain/job/query/dto/response/NearByJobResponse.java, src/main/java/spot/spot/domain/job/query/repository/dsl/SearchingListQueryDsl.java, src/main/java/spot/spot/domain/job/query/repository/dsl/_docs/SearchingListQueryDocs.java, src/main/java/spot/spot/domain/job/query/service/WorkerQueryService.java, src/main/java/spot/spot/domain/job/query/util/searching/SearchingJobJPQLQueryUtil.java, src/main/java/spot/spot/domain/job/query/util/searching/SearchingJobNativeQueryUtil.java, src/main/java/spot/spot/domain/job/query/util/searching/SearchingJobQueryDSLUtil.java, src/main/java/spot/spot/domain/job/v1/query/controller/WorkerQueryControllerV1.java, src/main/java/spot/spot/domain/job/v1/query/controller/_docs/WorkerQueryDocsV1.java, src/main/java/spot/spot/domain/job/v1/query/mapper/WorkerQueryMapperV1.java, src/main/java/spot/spot/domain/job/v1/query/repository/dsl/SearchingListQueryDslV1.java, src/main/java/spot/spot/domain/job/v1/query/repository/jpa/JobRepositoryV1.java, src/main/java/spot/spot/domain/job/v1/query/service/SearchingJobJpqlQueryUtilVV1.java, src/main/java/spot/spot/domain/job/v1/query/service/SearchingJobNativeQueryUtilVV1.java, src/main/java/spot/spot/domain/job/v1/query/service/SearchingJobQueryDslVersionUtilVV1.java, src/main/java/spot/spot/domain/job/v1/query/service/WorkerQueryServiceV1.java, src/main/java/spot/spot/domain/job/v1/query/service/_docs/SearchingJobQueryVersionUtilV1.java
- #214 
-  (1) 위 사진과 같이, 반경 내에 존재하는 객체를 찾기 위해 DB 상 모든 객체를 상대로 **`Haver-sine` 공식 계산**을 하였습니다.  그 결과 실행 계획에서 `scan type`이 **`all`**이 나왔습니다.
- (2) `scan-type: all` 이란 원하는 데이터를 찾기 위해서 테이블 풀 스켄을 때린다는 말입니다. 이는 데이터가 늘어남에 따라 심각한 성능 저하를 초래합니다. 이로 인해, 데이터 부하가 심해질수록 오류율이 늘고, 응답 시간이 30초를 넘어가는 사태가 발생되었습니다.
- (3) B-tree 기반 인덱싱이 소용 없었습니다.
위와 같이 index를 적용했으나, B-tree 인덱스는 **값의 크고 작음을 비교한 빠른 조회**에서만 효과를 발휘합니다. 따라서, **Haver-sine**을 활용한 공간 계산에서는 index가 전혀 쓰이지 않았습니다. 
다음은 실행했던 내용의 실행계획입니다. 
```sql
EXPLAIN
SELECT *, (6371 * ACOS(COS(RADIANS(37.5665)) * COS(RADIANS(lat)) * COS(RADIANS(lng) - RADIANS(126.9780)) + SIN(RADIANS(37.5665)) * SIN(RADIANS(lat))))
AS distance
FROM job
WHERE job.started_at != null
AND (6371 * ACOS(COS(RADIANS(37.5665)) * COS(RADIANS(lat)) * COS(RADIANS(lng) - RADIANS(126.9780)) + …
```
=> FEAT: mySQL 방언, 공간 데이터 활용 없이 순수 쿼리 최적화

src/main/java/spot/spot/domain/job/command/controller/WorkerCommandController.java, src/main/java/spot/spot/domain/job/command/dto/response/RegisterJobResponse.java, src/main/java/spot/spot/domain/job/command/mapper/ClientCommandMapper.java, src/main/java/spot/spot/domain/job/command/mapper/NotificationMapper.java, src/main/java/spot/spot/domain/job/command/service/ClientCommandService.java, src/main/java/spot/spot/domain/job/command/service/WorkerCommandService.java, src/main/java/spot/spot/domain/job/command/service/_docs/WorkerCommandServiceDocs.java, src/main/java/spot/spot/domain/job/v1/command/service/ClientCommandVersion1Service.java, src/main/java/spot/spot/domain/notification/command/dto/response/FcmDTO.java, src/main/java/spot/spot/domain/notification/command/service/FcmMessageUtil.java
=> FIX: FCM 양방향 송수신 설정 및 알림 저장 로직, 전 매칭 생애주기에 구현

src/main/java/spot/spot/domain/notification/query/dto/response/NotificationResponse.java, src/main/java/spot/spot/domain/notification/query/repository/SearchingNotificationListDsl.java
- resolve #244 
필드 주입은 보안과 데이터 무결성을 해치므로 지양해야하는 코드라고 배웠는데, 제가 규칙을 어기고 있었네요. 다시 고쳐놨습니다. 감사합니다.
=> FIX: NOTIFICATION ERROR 해결 

src/main/java/spot/spot/domain/job/command/service/WorkerCommandService.java
- #237 
Member owner = changeJobStatusCommandDsl.getJobsOwner(job.getId());
FcmDTO msg = fcmMessageUtil.startJob2ClientMsg(owner.getNickname(), worker.getNickname(), job.getTitle());
```
이 부분에서 job.getId() 가 아니라 matching.getId()를 보내고 있었습니다.
시나리오 테스트를 하며, 알림 수정으로 인해 생겼던 오류를 잡았습니다.
=> FIX: 일 완료 버튼 안되는 것 수정

src/main/java/spot/spot/domain/job/command/service/ClientCommandService.java, src/main/java/spot/spot/domain/job/command/service/WorkerCommandService.java, src/main/java/spot/spot/domain/notification/command/service/FcmAsyncSendingUtil.java, src/main/java/spot/spot/global/retry/ExponentialJitterBackOffPolicy.java, src/main/java/spot/spot/global/retry/RetryConfig.java
- resolve #261 
지수 백오프 동안 동시에 요청이 들어온다면, 같은 지수 시간에 동시에 요청을 하기 때문에, 동시성에 따른 큐 진입 실패자들의 동시 요청을 분산하진 못하고 뒤로 미루는 느낌입니다.
여기에 난수 알고리즘을 통한 지연 변이를 넣어서, 재시도 요청의 시간대를 세밀하게 분산하도록 조치 했습니다.
=> FEAT: Thread 거절에 대한 재시도 로직 에서 지연 변이 로직 추가

src/main/java/spot/spot/global/config/AsyncConfig.java, src/main/java/spot/spot/global/retry/ExponentialJitterBackOffPolicy.java
- resolve #261
- 저번 상태 경과 보고 
보시면 이제 서버에 500RPS 까지 제대로 가고 있습니다. 저번에 에러와 지연 처리로 인해, 모든 요청이 정확히 가지 않았던 것에 비하면 더 좋아진 성과 입니다.
응답 시간도 좋아졌습니다. 이제 500RPS 전까지는 에러 없이 들어가는 것을 볼 수 있습니다.
에러율도 5%이하로 줄었고 450RPS 유지까지는 에러율이 0%였습니다.
이제 병목 지점을 거의 잡은 것 같아서, 조금만 config 값을 더 늘려서, 저희 테스트의 목표인 RPS를 오류율 0%에 응답시간 3초 이내로 끊을 수 있도록 해보겠습니다.
=> FEAT: ASYNC 대기 큐 값 늘리기

src/main/java/spot/spot/global/config/AsyncConfig.java, src/main/java/spot/spot/global/retry/ExponentialJitterBackOffPolicy.java
- resolved #261 
오히려 대기 큐를 늘리고, max Interval를 늘려 재시도 시간을 늘리니까, 에러가 더 빨리 터졌습니다. 450RPS를 들어가는 시점에서 에러가 터져서, 그 부분 다시 원상 복귀 해놓겠습니다.
=> FEAT: ASYNC 대기 큐 다시 되돌리기

src/main/java/spot/spot/domain/job/query/repository/dsl/SearchingListQueryDsl.java, src/main/java/spot/spot/domain/notification/command/service/FcmMessageUtil.java
=> FIX: 부하 지속 시 생기는 FCM MESSAGE 만들기 관련 StringBuilder 혼용 사용 에러 잡기 2차 도전

src/main/java/spot/spot/global/response/handler/GlobalExceptionHandler.java
=> CHORE: 에러로그 한 줄에 출력.

src/main/java/spot/spot/domain/notification/command/service/FcmMessageUtil.java, src/main/java/spot/spot/global/response/handler/GlobalExceptionHandler.java
=> FIX: 에러 로그를 한 줄에 출력

build.gradle, src/main/java/spot/spot/domain/job/query/dto/response/NearByJobResponse.java, src/main/java/spot/spot/domain/job/query/repository/dsl/SearchingListQueryDsl.java, src/main/java/spot/spot/domain/job/query/util/caching/AsyncGeoCacheScheduler.java, src/main/java/spot/spot/domain/job/query/util/caching/GeoCacheWarmUp.java, src/main/java/spot/spot/domain/job/query/util/caching/GeoHashUtil.java, src/main/java/spot/spot/domain/job/query/util/caching/JobGeoCacheSyncService.java, src/main/java/spot/spot/domain/job/query/util/caching/JobGeoCacheSyncUtil.java, src/main/java/spot/spot/global/config/CacheConfig.java, src/main/java/spot/spot/global/response/format/ErrorCode.java, src/main/java/spot/spot/global/util/ConstantUtil.java
=> FEAT: Caffine L1 캐싱만을 이용한 Read-Through 기반 캐싱 적용 
