6-SPOT/spot-be

src/main/java/spot/spot/global/config/GlobalResponseHandler.java

chore: Job Entity 설정 및 업로드

---

src/main/java/spot/spot/pay/entity/KlayAboutJob.java
src/main/java/spot/spot/pay/entity/PayHistory.java
src/main/java/spot/spot/pay/entity/Point.java

chore: entity 설정

---

src/main/java/spot/spot/domain/pay/entity/KlayAboutJob.java
src/main/java/spot/spot/global/klaytn/api/ExchangeRateByBithumbApi.java
src/main/java/spot/spot/global/response/format/ErrorCode.java
src/main/resources/application.properties
src/test/java/spot/spot/global/klaytn/api/ExchangeRateByBithumbApiTest.java

feat: 빗썸 오픈 api로 kaia/krw 환율 변환

---

.gitignore
build.gradle
src/main/java/spot/spot/domain/job/entity/Certification.java
src/main/java/spot/spot/domain/job/entity/Job.java
src/main/java/spot/spot/domain/job/entity/Matching.java
src/main/java/spot/spot/domain/job/repository/CertificationRepository.java
src/main/java/spot/spot/domain/job/repository/HashTagRepository.java
src/main/java/spot/spot/domain/job/repository/JobRepository.java
src/main/java/spot/spot/domain/job/repository/MatchingRepository.java
src/main/java/spot/spot/domain/member/entity/Ability.java
src/main/java/spot/spot/domain/member/entity/Member.java
src/main/java/spot/spot/domain/member/entity/Worker.java
src/main/java/spot/spot/domain/member/entity/WorkerAbility.java
src/main/java/spot/spot/domain/member/repository/AbilityRepository.java
src/main/java/spot/spot/domain/member/repository/MemberRepository.java
src/main/java/spot/spot/domain/member/repository/WorkerAbilityRepository.java
src/main/java/spot/spot/domain/member/repository/WorkerRepository.java
src/main/resources/application-db.yml
src/main/resources/application.properties
src/main/resources/application.yml

- resolved #19 
- resolved #24 
H2는 기본 실행하면 적용됩니다.
> MYSQL로 테스트 해보고 싶으신 분
`SPRING_PROFILES_ACTIVE=mysql ./gradlew bootRun` 로 SPIRNG 실행

feat: 일 관련 부가 Entity 추가 및 연관 관계 작성 & MySQL 장착

---

build.gradle
src/main/java/spot/spot/global/klaytn/ConnectToKlaytnNetwork.java
src/main/java/spot/spot/global/klaytn/api/ExchangeRateByBithumbApi.java
src/main/java/spot/spot/global/response/format/ErrorCode.java
src/test/java/spot/spot/global/config/ConnectToKlaytnNetworkTest.java
src/test/java/spot/spot/global/klaytn/api/ExchangeRateByBithumbApiTest.java

- #30 
- #38 
에러 테스트 케이스를 추가하는 과정에 필요한 에러케이스 추가와 gradle 설정이 에러가나서 삭제하였습니다.

TEST: 스마트 컨트랙트 메서드 에러케이스 테스트

---

src/main/java/spot/spot/domain/pay/entity/KlayAboutJob.java
src/main/java/spot/spot/domain/pay/entity/PayHistory.java
src/main/java/spot/spot/domain/pay/entity/Point.java

chore: pay, payhistory, klayAboutJob 엔터티 수정

---

build.gradle
src/main/java/spot/spot/global/config/FireBaseConfig.java
src/main/java/spot/spot/global/config/PropertyPrinter.java
src/main/java/spot/spot/global/response/handler/GlobalVaultResponseKeys.java
src/main/resources/application-dev.yml
src/main/resources/application.yml

Vault를 이용해 key값들을 가져와 사용하도록 변경했습니다. 아직 배포까지 성공하지 않았지만 성공시 바로 문서화 하도록 하겠습니다.

Feat/#58 Vault 설정 완료

---

.github/workflows/dev-test-actions.yml
src/main/java/spot/spot/global/config/PropertyPrinter.java

Github Action 동작시 테스트가 잘 동작하는지 확인합니다.
잘 동작합니다!!

chore: Github Action test 체크

---

src/main/resources/application-dev.yml

fix: dev kakao 로그인 redirect_url 수정

---

src/main/resources/application-dev.yml

fix: kakao redirect_url

---

src/main/java/spot/spot/global/config/SecurityConfig.java

fix: security /api/** 경로삭제

---

src/main/java/spot/spot/domain/member/service/OAuth2FailureHandler.java
src/main/resources/application-dev.yml

chore: error log trace 추가

---

src/main/java/spot/spot/global/config/SecurityConfig.java

/api/** security 허용했습니다. 개발용으로 추후 삭제할 예정입니다

chore: 개발용 /api/** security 허용

---

src/main/java/spot/spot/domain/job/_docs/Job4ClientDocs.java
src/main/java/spot/spot/domain/job/_docs/Job4WorkerDocs.java
src/main/java/spot/spot/domain/job/controller/Job4ClientController.java
src/main/java/spot/spot/domain/job/controller/Job4WorkerController.java
src/main/java/spot/spot/domain/job/dto/request/JobRequest.java
src/main/java/spot/spot/domain/job/dto/response/AttenderResponse.java
src/main/java/spot/spot/domain/job/dto/response/JobWithOwnerReponse.java
src/main/java/spot/spot/domain/job/mapper/Job4ClientMapper.java
src/main/java/spot/spot/domain/job/mapper/Job4WorkerMapper.java
src/main/java/spot/spot/domain/job/repository/dsl/JobStatusQueryDsl.java
src/main/java/spot/spot/domain/job/repository/dsl/WorkerSearchingQuerydsl.java
src/main/java/spot/spot/domain/job/service/Job4ClientService.java
src/main/java/spot/spot/domain/job/service/Job4WorkerService.java
src/main/java/spot/spot/domain/notification/service/FcmUtil.java
src/main/java/spot/spot/global/response/format/ErrorCode.java
src/main/resources/application-local.yml

- resolved #85
- resolved #88
Key Change 및 스크린샷은 출근 후 찍겠습니다.

FEAT: 일 신청자 리스트 API 완성 + 해결사의 일 시작하기 API 완성

---

src/main/java/spot/spot/domain/job/_docs/Job4ClientDocs.java
src/main/java/spot/spot/domain/job/controller/Job4ClientController.java
src/main/java/spot/spot/domain/job/dto/request/YesOrNoOfClientRequest.java
src/main/java/spot/spot/domain/job/service/Job4ClientService.java
src/main/java/spot/spot/domain/notification/service/FcmUtil.java
src/main/java/spot/spot/global/response/handler/GlobalExceptionHandler.java

- resolve #87
- fix #86 
다음으로 출발~

FEAT: 의뢰자가 해결사의 요청 중 하나를 승낙하는 API 완성

---

src/main/java/spot/spot/domain/job/_docs/Job4ClientDocs.java
src/main/java/spot/spot/domain/job/_docs/Job4WorkerDocs.java
src/main/java/spot/spot/domain/job/controller/Job4ClientController.java
src/main/java/spot/spot/domain/job/controller/Job4WorkerController.java
src/main/java/spot/spot/domain/job/dto/request/YesOrNo2ClientsRequest.java
src/main/java/spot/spot/domain/job/dto/request/YesOrNo2WorkersRequest.java
src/main/java/spot/spot/domain/job/dto/request/YesOrNoOfClientRequest.java
src/main/java/spot/spot/domain/job/service/Job4ClientService.java
src/main/java/spot/spot/domain/job/service/Job4WorkerService.java
src/main/java/spot/spot/domain/notification/service/FcmUtil.java
src/main/java/spot/spot/global/response/handler/GlobalExceptionHandler.java

Feat: 해결사가 의뢰인의 요청 승낙 혹은 거절 하는 API 완성 및 FCM 알림 보내기 구현 

---

src/main/java/spot/spot/domain/job/_docs/Job4ClientDocs.java
src/main/java/spot/spot/domain/job/_docs/Job4WorkerDocs.java
src/main/java/spot/spot/domain/job/controller/Job4ClientController.java
src/main/java/spot/spot/domain/job/controller/Job4WorkerController.java
src/main/java/spot/spot/domain/job/dto/request/YesOrNo2ClientsRequest.java
src/main/java/spot/spot/domain/job/dto/request/YesOrNo2WorkersRequest.java
src/main/java/spot/spot/domain/job/dto/request/YesOrNoOfClientRequest.java
src/main/java/spot/spot/domain/job/service/Job4ClientService.java
src/main/java/spot/spot/domain/job/service/Job4WorkerService.java
src/main/java/spot/spot/domain/notification/service/FcmUtil.java
src/main/java/spot/spot/global/response/handler/GlobalExceptionHandler.java

FIX: 해결사의 일 해결 시작하기 API, 트랜잭션 영속성 유지하여 수정 오류 안 나도록 조치

---

src/main/java/spot/spot/domain/job/_docs/Job4ClientDocs.java
src/main/java/spot/spot/domain/job/_docs/Job4WorkerDocs.java
src/main/java/spot/spot/domain/job/controller/Job4ClientController.java
src/main/java/spot/spot/domain/job/controller/Job4WorkerController.java
src/main/java/spot/spot/domain/job/repository/dsl/ChangeJobStatusDsl.java
src/main/java/spot/spot/domain/job/repository/jpa/MatchingRepository.java
src/main/java/spot/spot/domain/job/service/Job4ClientService.java
src/main/java/spot/spot/domain/job/service/Job4WorkerService.java
src/main/java/spot/spot/domain/job/service/JobUtil.java
src/main/java/spot/spot/global/response/format/ErrorCode.java
src/main/java/spot/spot/global/scheduler/SchedulingConfig.java
src/main/java/spot/spot/global/scheduler/SchedulingTask.java

- close #120 
- #119 의 취소 요청을 먼저 날렸습니다.
- 이후 삭제 조치를 하였습니다.

FEAT: 해결사 쪽에서 일 재개 응답

---

src/main/java/spot/spot/domain/job/service/Job4ClientService.java
src/main/java/spot/spot/domain/pay/entity/KlayAboutJob.java
src/main/java/spot/spot/domain/pay/entity/PayHistory.java
src/main/java/spot/spot/domain/pay/repository/PayQueryRepository.java
src/main/java/spot/spot/domain/pay/service/PayService.java
src/main/java/spot/spot/global/response/format/ErrorCode.java

fix : redirect_url 수정

---

src/main/java/spot/spot/domain/pay/service/PayService.java
src/main/resources/application-dev.yml
src/main/resources/application-local.yml

- #124 
- dev와 local에서 반영되는 값을 동적으로 변경하였습니다. 
- local에서는 localhost로 redirect를 하고, dev에서는 ilmatch.net으로 가게됩니다.

refactor: dev, local kakaoPay redirect_url 동적 설정

---

src/main/java/spot/spot/global/security/util/OAuth2SuccessHandler.java

feat: local,dev 카카오 로그인 redirect 분리

---

src/main/java/spot/spot/domain/job/repository/jpa/JobRepository.java
src/main/java/spot/spot/domain/job/service/Job4ClientService.java
src/main/java/spot/spot/domain/pay/controller/PayController.java
src/main/java/spot/spot/domain/pay/entity/dto/request/PayApproveRequestDto.java
src/main/java/spot/spot/domain/pay/service/PayService.java

- #128 
카카오페이, 카카오 로그인 redirect_url과 서비스에서 변경 사항을 업데이트하였습니다.

fix: 카카오페이, 카카오 로그인 백엔드 코드 수정

---

src/main/java/spot/spot/domain/job/_docs/Job4ClientDocs.java
src/main/java/spot/spot/domain/job/controller/Job4ClientController.java
src/main/java/spot/spot/domain/job/dto/response/JobResponse.java
src/main/java/spot/spot/domain/job/dto/response/JobSituationResponse.java
src/main/java/spot/spot/domain/job/mapper/Job4ClientMapper.java
src/main/java/spot/spot/domain/job/mapper/Job4WorkerMapper.java
src/main/java/spot/spot/domain/job/repository/dsl/SearchingListDsl.java
src/main/java/spot/spot/domain/job/service/Job4ClientService.java
src/main/java/spot/spot/global/response/handler/GlobalExceptionHandler.java
src/main/java/spot/spot/global/response/handler/GlobalResponseHandler.java

- close #134 
- resolve #131
Mapper 없이 queryDSL에서 직접 변환 했습니다. 유지 보수성은 떨어지지만, join -> tuple -> mapper -> dto가 너무 변환 로직이 많아서 성능 저하될 가능성이 다분하여 이렇게 두었습니다. 이것도 두 개 비교해보고 하나 선택하겠습니다.
저번에 *'Security Error를 수정하며 필수적인 공통 에러는 감싸지 말고 지나가세요'* 로직도 지워버려서 복구 했습니다.
```json
{
"status": "success",
"message": "정상적으로 처리하였습니다.",
"data": [
{
"jobId": 1,
"title": "친절한 고객 응대",
"img": null,
"content": "신속한 작업 가능",
"status": "YES",
"memberId": 2,
"nickName": "김시우",
"phone": "13257067241"
},
{
"jobId": 1,
"title": "친절한 고객 응대",
"img": null,
"content": "신속한 작업 가능",
"status": "ATTENDER",
"memberId": 3,
"nickName": "최건우",
"phone": "74546165607"
},
{
"jobId": 1,
"title": "친절한 고객 응대",
"img":null,
"content": "신속한 작업 가능",
"status": "ATTENDER",
"memberId": 4,
"nickName": "임도윤",
"phone": "28163955726"
},
{
"jobId": 1, …
```

FEAT: 내가 맡긴 일 현황 한 눈에 보기 API 완성

---

src/main/java/spot/spot/domain/job/_docs/Job4ClientDocs.java
src/main/java/spot/spot/domain/job/_docs/Job4WorkerDocs.java
src/main/java/spot/spot/domain/job/controller/Job4ClientController.java
src/main/java/spot/spot/domain/job/controller/Job4WorkerController.java
src/main/java/spot/spot/domain/job/dto/response/JobResponse.java
src/main/java/spot/spot/domain/job/dto/response/JobSituationResponse.java
src/main/java/spot/spot/domain/job/entity/Certification.java
src/main/java/spot/spot/domain/job/mapper/Job4ClientMapper.java
src/main/java/spot/spot/domain/job/mapper/Job4WorkerMapper.java
src/main/java/spot/spot/domain/job/repository/dsl/SearchingListDsl.java
src/main/java/spot/spot/domain/job/repository/jpa/CertificationRepository.java
src/main/java/spot/spot/domain/job/service/Job4ClientService.java
src/main/java/spot/spot/domain/job/service/Job4WorkerService.java
src/main/java/spot/spot/global/response/handler/GlobalExceptionHandler.java
src/main/java/spot/spot/global/response/handler/GlobalResponseHandler.java

FEAT: 일 하고 있어요~ 증명 사진 제출 API 완성

---

src/main/java/spot/spot/domain/job/_docs/Job4ClientDocs.java
src/main/java/spot/spot/domain/job/_docs/Job4WorkerDocs.java
src/main/java/spot/spot/domain/job/controller/Job4ClientController.java
src/main/java/spot/spot/domain/job/controller/Job4WorkerController.java
src/main/java/spot/spot/domain/job/dto/response/JobResponse.java
src/main/java/spot/spot/domain/job/dto/response/JobSituationResponse.java
src/main/java/spot/spot/domain/job/entity/Certification.java
src/main/java/spot/spot/domain/job/mapper/Job4ClientMapper.java
src/main/java/spot/spot/domain/job/mapper/Job4WorkerMapper.java
src/main/java/spot/spot/domain/job/repository/dsl/SearchingListDsl.java
src/main/java/spot/spot/domain/job/repository/jpa/CertificationRepository.java
src/main/java/spot/spot/domain/job/service/Job4ClientService.java
src/main/java/spot/spot/domain/job/service/Job4WorkerService.java
src/main/java/spot/spot/global/response/handler/GlobalExceptionHandler.java
src/main/java/spot/spot/global/response/handler/GlobalResponseHandler.java

FEAT:  해결사 용 일 완료 버튼 API 완성

---

src/main/java/spot/spot/domain/job/_docs/Job4ClientDocs.java
src/main/java/spot/spot/domain/job/_docs/Job4WorkerDocs.java
src/main/java/spot/spot/domain/job/controller/Job4ClientController.java
src/main/java/spot/spot/domain/job/controller/Job4WorkerController.java
src/main/java/spot/spot/domain/job/dto/response/JobResponse.java
src/main/java/spot/spot/domain/job/dto/response/JobSituationResponse.java
src/main/java/spot/spot/domain/job/entity/Certification.java
src/main/java/spot/spot/domain/job/entity/MatchingStatus.java
src/main/java/spot/spot/domain/job/mapper/Job4ClientMapper.java
src/main/java/spot/spot/domain/job/mapper/Job4WorkerMapper.java
src/main/java/spot/spot/domain/job/repository/dsl/ChangeJobStatusDsl.java
src/main/java/spot/spot/domain/job/repository/dsl/SearchingListDsl.java
src/main/java/spot/spot/domain/job/repository/jpa/CertificationRepository.java
src/main/java/spot/spot/domain/job/service/Job4ClientService.java
src/main/java/spot/spot/domain/job/service/Job4WorkerService.java
src/main/java/spot/spot/global/response/handler/GlobalExceptionHandler.java
src/main/java/spot/spot/global/response/handler/GlobalResponseHandler.java

FEAT: 일 해결 확정 혹은 반려 API 완성

---

src/main/java/spot/spot/domain/job/_docs/Job4ClientDocs.java
src/main/java/spot/spot/domain/job/_docs/Job4WorkerDocs.java
src/main/java/spot/spot/domain/job/controller/Job4WorkerController.java
src/main/java/spot/spot/domain/job/repository/dsl/SearchingListDsl.java
src/main/java/spot/spot/domain/job/service/Job4WorkerService.java
src/main/java/spot/spot/domain/job/service/JobStreamingService.java

HOT FIX: DOCS 수정 및 내가 맡은 일 현황 API 완성

---

src/main/java/spot/spot/domain/member/service/MemberService.java
src/test/java/spot/spot/domain/job/controller/Job4ClientControllerTest.java

- #157 
테스트 코드를 작성하지 않은 부분이라 사소한 오류가 발생했습니다. ㅠ

fix: kakao 간편 로그인 오류

---

src/main/java/spot/spot/domain/job/service/Job4ClientService.java
src/test/java/spot/spot/domain/job/controller/Job4ClientControllerTest.java
src/test/java/spot/spot/domain/pay/controller/PayControllerExceptionTest.java
src/test/java/spot/spot/domain/pay/controller/PayControllerTest.java
src/test/java/spot/spot/domain/pay/controller/PointControllerExceptionTest.java
src/test/java/spot/spot/domain/pay/controller/PointControllerTest.java
src/test/java/spot/spot/domain/pay/service/PayServiceTest.java

- #161 
깊이 있게 생각을 못했습니다.. 괜히 pr을 한번 더 해야하네요

fix: updateTidToJob 메서드 @Transactional 추가, tid 업데이트

---

src/main/java/spot/spot/domain/member/repository/MemberRepository.java
src/main/java/spot/spot/domain/pay/controller/PayController.java
src/main/java/spot/spot/domain/pay/repository/PointRepository.java
src/main/java/spot/spot/domain/pay/service/PointService.java
src/test/java/spot/spot/domain/pay/service/PointServiceExceptionTest.java
src/test/java/spot/spot/domain/pay/service/PointServiceTest.java

refactor: 포인트 등록 동시성 락 문제

---

src/main/java/spot/spot/domain/job/service/ClientService.java
src/main/java/spot/spot/domain/job/util/JobUtil.java
src/main/java/spot/spot/domain/pay/repository/PayRepositoryDsl.java
src/main/java/spot/spot/domain/pay/service/PayService.java
src/test/java/spot/spot/domain/pay/repository/PayRepositoryDslTest.java
src/test/java/spot/spot/domain/pay/service/PayServiceTest.java

feat: 일 완료, 일 철회 시 결제서비스 연결

---

src/main/java/spot/spot/domain/job/command/dto/response/JobSituationResponse.java
src/main/java/spot/spot/domain/job/query/repository/dsl/SearchingListQueryDsl.java

FIX: 일 현황에 아무도 신청 안한 일도 올라 오도록 추가 isOwner(일의 주인 인가) 추가

---

src/main/resources/application-localmysql.yml

fix: 카카오 리다이렉트 경로 오류

---

src/main/java/spot/spot/domain/job/query/controller/WorkerQueryController.java
src/main/java/spot/spot/domain/job/query/service/WorkerQueryService.java

FIX: 근처 일 찾기 api (/api/job/worker/search) default 값 안 나가는 오류 수정

---

src/main/java/spot/spot/domain/job/command/repository/jpa/CertificationRepository.java
src/main/java/spot/spot/domain/job/query/controller/ClientQueryController.java
src/main/java/spot/spot/domain/job/query/controller/WorkerQueryController.java
src/main/java/spot/spot/domain/job/query/controller/_docs/ClientQueryDocs.java
src/main/java/spot/spot/domain/job/query/controller/_docs/WorkerQueryDocs.java
src/main/java/spot/spot/domain/job/query/dto/response/AttenderResponse.java
src/main/java/spot/spot/domain/job/query/dto/response/CertificationImgResponse.java
src/main/java/spot/spot/domain/job/query/mapper/ClientQueryMapper.java
src/main/java/spot/spot/domain/job/query/repository/dsl/SearchingListQueryDsl.java
src/main/java/spot/spot/domain/job/query/repository/dsl/_docs/SearchingListQueryDocs.java
src/main/java/spot/spot/domain/job/query/service/ClientQueryService.java
src/main/java/spot/spot/domain/job/query/service/PositionQueryService.java
src/main/java/spot/spot/domain/job/query/service/WorkerQueryService.java
src/main/java/spot/spot/domain/job/query/service/_docs/ClientQueryServiceDocs.java
src/main/java/spot/spot/domain/job/query/service/_docs/PositionQueryServiceDocs.java
src/main/java/spot/spot/domain/job/query/service/_docs/WorkerQueryServiceDocs.java
src/main/resources/application-test.yml

- close #202
제가 이미지 링크를 null로 저장해서 밑과 같이 뜨네요 ㅎ

FEAT: 해결사의 인증 사진 리스트 조회 API 완성 

---

src/main/java/spot/spot/domain/job/command/service/ClientCommandService.java
src/main/java/spot/spot/domain/job/command/service/WorkerCommandService.java
src/main/java/spot/spot/domain/notification/command/repository/NotificationRepository.java
src/main/java/spot/spot/domain/notification/command/service/FcmAsyncSendingUtil.java
src/main/java/spot/spot/domain/notification/command/service/FcmMessageUtil.java
src/main/java/spot/spot/domain/notification/command/service/FcmService.java
src/main/java/spot/spot/domain/notification/query/controller/NotificationQueryController.java
src/main/java/spot/spot/domain/notification/query/controller/_docs/NotificationQueryControllerDocs.java
src/main/java/spot/spot/domain/notification/query/dto/response/NotificationResponse.java
src/main/java/spot/spot/domain/notification/query/repository/SearchingNotificationListDsl.java
src/main/java/spot/spot/domain/notification/query/service/NotificationService.java

- close #190
querydsl에서 직접 매핑해버려서 Mapper가 따로 필요 있나 싶습니다. 이것도 한 번 체크해봐야겠습니다.

FEAT: 채팅방 알림 리스트 API 구현 

---

src/main/java/spot/spot/domain/job/query/controller/WorkerQueryController.java
src/main/java/spot/spot/domain/job/query/controller/_docs/WorkerQueryDocs.java
src/main/java/spot/spot/domain/job/query/repository/dsl/SearchingListQueryDsl.java
src/main/java/spot/spot/domain/job/query/repository/dsl/_docs/SearchingListQueryDocs.java
src/main/java/spot/spot/domain/job/query/service/WorkerQueryService.java
src/main/java/spot/spot/domain/job/query/service/_docs/WorkerQueryServiceDocs.java

FIX: workerId 없이 jobId로만 원하는 값 가져오기 로직 구현 완료

---

src/main/java/spot/spot/domain/job/command/service/ClientCommandService.java
src/main/java/spot/spot/domain/job/command/util/ReservationCancelUtil.java
src/main/java/spot/spot/domain/pay/entity/PayHistory.java
src/main/java/spot/spot/domain/pay/repository/PayRepositoryDsl.java
src/main/java/spot/spot/domain/pay/service/PayMockService.java
src/main/java/spot/spot/domain/pay/service/PayService.java
src/test/java/spot/spot/domain/pay/repository/PayRepositoryDslTest.java
src/test/java/spot/spot/domain/pay/util/PayUtilTest.java

bug: payHistoryDslRepository 단일 값이 아닌 리스트로 나오는 오류 수정

---

src/main/java/spot/spot/domain/chat/service/ChatService.java
src/main/java/spot/spot/global/stomp/StompHandler.java

채팅이 보낸시간 순으로 정렬이 안되서 빠르게 수정했습니다.

Feat/#207 채팅 보낸시간 추가

---

build.gradle
src/main/java/spot/spot/domain/job/command/controller/ClientCommandController.java
src/main/java/spot/spot/domain/job/command/controller/_docs/ClientCommandDocs.java
src/main/java/spot/spot/domain/job/command/dto/request/ConfirmOrRejectRequest.java
src/main/java/spot/spot/domain/job/command/service/ClientCommandService.java
src/main/java/spot/spot/domain/job/command/service/_docs/ClientCommandServiceDocs.java
src/main/java/spot/spot/domain/member/repository/MemberQueryRepository.java

FIX: 확정 혹은 거절 에서 WorkerId 제외

---

src/main/java/spot/spot/domain/pay/service/PayMockService.java
src/main/java/spot/spot/domain/pay/service/PayService.java
src/main/java/spot/spot/global/klaytn/ConnectToKlaytnNetwork.java

fix: double -> int형 변환 시 0 이하 버림 문제

---

src/main/java/spot/spot/domain/job/command/controller/ClientCommandController.java
src/main/java/spot/spot/domain/job/command/service/ClientCommandService.java
src/main/java/spot/spot/domain/job/v1/command/controller/ClientCommandVersion1Controller.java
src/main/java/spot/spot/domain/job/v1/command/controller/_docs/ClientCommandVersion1Docs.java
src/main/java/spot/spot/domain/job/v1/command/service/ClientCommandVersion1Service.java
src/main/java/spot/spot/domain/job/v1/query/controller/_docs/WorkerQueryVersion1Docs.java
src/main/java/spot/spot/global/healthcheck/command/controller/_docs/HealthCheckCommandDocs.java
src/main/java/spot/spot/global/healthcheck/query/controller/_docs/HealthCheckQueryDocs.java

CHORE: V1 버전 API 컨트롤러 서비스 모두 v1 폴더로 이동

---

build.gradle
src/main/java/spot/spot/domain/job/command/entity/Job.java
src/main/java/spot/spot/domain/job/command/entity/Matching.java
src/main/java/spot/spot/domain/job/command/mapper/ClientCommandMapper.java
src/main/java/spot/spot/domain/job/command/mapper/WorkerCommandMapper.java
src/main/java/spot/spot/domain/job/command/repository/dsl/WorkerUpdatingCommandDsl.java
src/main/java/spot/spot/domain/job/command/service/ClientCommandService.java
src/main/java/spot/spot/domain/job/command/service/WorkerCommandService.java
src/main/java/spot/spot/domain/member/entity/Member.java
src/main/java/spot/spot/global/config/GeometryFactoryConfig.java
src/main/resources/application-dev.yml
src/main/resources/application-test.yml

FEAT: DB 최신화 (단순 위도 경도 저장 -> mySQL POINT (공간 객체 - 세계적으로 GPS에 활용됨) 로 변환 및 관련 일 등록, 구직자 등록 로직 개선

---

src/main/java/spot/spot/domain/pay/controller/PointController.java
src/main/java/spot/spot/domain/pay/entity/Point.java
src/main/java/spot/spot/domain/pay/entity/dto/request/PointServeRequestDto.java
src/main/java/spot/spot/domain/pay/entity/dto/response/PointServeResponseDto.java
src/main/java/spot/spot/domain/pay/repository/PointRepository.java
src/main/java/spot/spot/domain/pay/service/PointService.java
src/test/java/spot/spot/domain/pay/repository/PointRepositoryTest.java
src/test/java/spot/spot/domain/pay/service/PayServiceTest.java
src/test/java/spot/spot/domain/pay/service/PointServiceExceptionTest.java
src/test/java/spot/spot/domain/pay/service/PointServiceTest.java
src/test/java/spot/spot/domain/pay/util/PayUtilTest.java

fix: 포인트 엔터티 수정

---

src/test/java/spot/spot/domain/pay/service/PayServiceTest.java
src/test/java/spot/spot/domain/pay/util/PayUtilTest.java

- #220 
결제 내역 리스트 반환 오류를 해결하기 위해 수정했던 메서드들로 인해 깨진 테스트 코드 수정입니다.

test: payService 로직 수정으로 인한 테스트 코드 변경

---

src/main/java/spot/spot/domain/pay/controller/PointController.java
src/main/java/spot/spot/domain/pay/repository/PointRepository.java
src/main/java/spot/spot/domain/pay/repository/PointRepositoryDsl.java
src/main/java/spot/spot/domain/pay/service/PointService.java

- #229 
낙관적 락 vs 비관적 락 배포서버에서 비교하기 위해 api를 생성하였습니다.

feat: 포인트 등록 낙관적 락 api 생성

---

build.gradle
src/main/java/spot/spot/domain/job/command/mapper/ClientCommandMapper.java
src/main/java/spot/spot/domain/job/command/mapper/WorkerCommandMapper.java
src/main/java/spot/spot/domain/job/query/repository/dsl/SearchingListQueryDsl.java
src/main/java/spot/spot/domain/job/query/repository/jpa/JobRepository.java
src/main/java/spot/spot/domain/job/query/util/DistanceCalculateUtil.java
src/main/java/spot/spot/domain/job/query/util/GeometryUtil.java
src/main/java/spot/spot/domain/job/query/util/_docs/GeometryUtilDocs.java
src/main/java/spot/spot/domain/job/v1/command/controller/_docs/ClientCommandVersion1Docs.java
src/main/java/spot/spot/domain/job/v1/query/service/SearchingJobJpqlQueryUtilV1.java
src/main/java/spot/spot/domain/job/v1/query/service/SearchingJobNativeQueryUtilV1.java
src/main/java/spot/spot/domain/job/v1/query/service/SearchingJobQueryDslUtilV1.java
src/main/java/spot/spot/domain/job/v1/query/service/WorkerQueryServiceV1.java
src/main/java/spot/spot/domain/job/v1/query/service/_docs/SearchingJobQueryUtilV1.java
src/main/java/spot/spot/domain/job/v2/query/controller/WorkerQueryControllerV2.java
src/main/java/spot/spot/domain/job/v2/query/controller/_docs/WorkerQueryDocsV2.java
src/main/java/spot/spot/domain/job/v2/query/repository/dsl/SearchingListQueryDslv2.java
src/main/java/spot/spot/domain/job/v2/query/repository/jpa/JobRepositoryV2.java
src/main/java/spot/spot/domain/job/v2/query/service/WorkerQueryServiceV2.java
src/main/java/spot/spot/domain/job/v2/query/util/SearchingJobQueryUtilV2.java
src/main/java/spot/spot/domain/job/v2/query/util/SearchingJobQueryUtilWithJpqlV2.java
src/main/java/spot/spot/domain/job/v2/query/util/SearchingJobQueryUtilWithNativeQueryV2.java
src/main/java/spot/spot/domain/job/v2/query/util/SearchingJobQueryUtilWithQuerydslV2.java
src/main/java/spot/spot/global/config/QuerydslConfig.java
src/main/resources/application.yml

FEAT: 표준 SQL 쿼리 최적화 + SPATIAL INDEX 공간 데이터 활용 쿼리 최적화, JDBC 커스터마이징

---

src/main/java/spot/spot/domain/job/command/mapper/WorkerCommandMapper.java
src/main/java/spot/spot/domain/job/command/repository/dsl/ChangeJobStatusCommandDsl.java
src/main/java/spot/spot/domain/job/command/repository/dsl/WorkerUpdatingCommandDsl.java
src/main/java/spot/spot/domain/job/command/repository/dsl/_docs/ChangeJobStatusCommandDocs.java
src/main/java/spot/spot/domain/job/command/service/WorkerCommandService.java
src/main/java/spot/spot/domain/notification/command/service/FcmMessageUtil.java
src/main/java/spot/spot/global/config/SwaggerConfig.java

HOT FIX: SWAGGER에 TEST 서버넷 URL 추가

---

src/main/java/spot/spot/domain/job/command/mapper/NotificationMapper.java
src/main/java/spot/spot/domain/job/command/mapper/WorkerCommandMapper.java
src/main/java/spot/spot/domain/notification/command/entity/Notification.java
src/main/java/spot/spot/domain/notification/query/repository/SearchingNotificationListDsl.java

HOT FIX: Notification 철자 에러 수정

---

src/main/java/spot/spot/domain/member/controller/MemberController.java
src/main/java/spot/spot/domain/member/dto/response/LoginResponseDto.java
src/main/java/spot/spot/domain/member/service/LoginFakeApiService.java
src/main/java/spot/spot/domain/member/service/MemberService.java
src/main/java/spot/spot/domain/pay/controller/PointController.java
src/main/java/spot/spot/domain/pay/entity/dto/response/PointServeResponseDto.java
src/main/java/spot/spot/domain/pay/repository/PointRepository.java
src/main/java/spot/spot/domain/pay/service/PayAPIRequestService.java
src/main/java/spot/spot/domain/pay/service/PayMockService.java
src/main/java/spot/spot/domain/pay/service/PointService.java
src/main/java/spot/spot/global/response/format/ErrorCode.java

feat: pay, login fake-api 추가

---

src/main/java/spot/spot/domain/review/controller/ReviewController.java
src/main/java/spot/spot/domain/review/controller/_docs/ReviewDocs.java
src/main/java/spot/spot/domain/review/dto/response/AuthoredReview.java
src/main/java/spot/spot/domain/review/dto/response/ReceivedReview.java
src/main/java/spot/spot/domain/review/repository/ReviewRepository.java
src/main/java/spot/spot/domain/review/repository/searchingReivewListDsl.java
src/main/java/spot/spot/domain/review/service/ReviewService.java

FEAT: 리뷰 LIST API 완성 및 페이지 네이션 적용 완료

---

src/main/java/spot/spot/domain/member/controller/MemberController.java
src/main/java/spot/spot/domain/member/dto/response/PointResponse.java
src/main/java/spot/spot/domain/pay/service/PayService.java
src/main/java/spot/spot/global/security/filter/OAuth2SuccessHandler.java

FEAT: 포인트 반환 api 추가 및 노예 1호 ip주소 redirect 추가

---

src/main/java/spot/spot/domain/member/_docs/MemberDocs.java
src/main/resources/application.yml

CHORE: TOKEN 수명 7일로 늘리기

---

src/main/java/spot/spot/global/healthcheck/query/controller/HealthCheckQueryController.java

feat: fake-api 서버 헬스체크 api

---

src/main/java/spot/spot/domain/job/command/service/ClientCommandService.java

- #237 
S3 돈이 많이 들까봐 이렇게 바꿉니다.

FIX: 일 등록 시 사진 없어도 되도록 수정 (for Test)

---

src/main/java/spot/spot/domain/job/command/service/ClientCommandService.java

FIX: PAY 강결합 주석 처리

---

.github/workflows/auto-assign.yml
.github/workflows/dev-test-actions.yml

CHORE: 필요 없는 yml 지우기

---

src/main/resources/application-test.yml

- #261
```txt
[31m예상치 못한 에러: [0m 
org.springframework.transaction.CannotCreateTransactionException: Could not open JPA EntityManager for transaction
at org.springframework.orm.jpa.JpaTransactionManager.doBegin(JpaTransactionManager.java:466)
at org.springframework.transaction.support.AbstractPlatformTransactionManager.startTransaction(AbstractPlatformTransactionManager.java:532)
at org.springframework.transaction.support.AbstractPlatformTransactionManager.getTransaction(AbstractPlatformTransactionManager.java:405)
at org.springframework.transaction.interceptor.TransactionAspectSupport.createTransactionIfNecessary(TransactionAspectSupport.java:639)
at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:374)
at …
```

CHORE: max- connection-pool size 늘리기

---

build.gradle
src/main/java/spot/spot/domain/chat/controller/KafkaStompChatController.java
src/main/java/spot/spot/domain/chat/controller/SimpleStompChatController.java
src/main/java/spot/spot/domain/chat/kafka/ConsumerService.java
src/main/java/spot/spot/domain/chat/repository/ChatRoomCustomRepositoryImpl.java
src/main/java/spot/spot/domain/chat/repository/MongoChatMessageRepository.java
src/main/java/spot/spot/domain/chat/service/MongoChatService.java
src/main/java/spot/spot/domain/chat/service/SimpleChatService.java
src/main/java/spot/spot/global/kafka/KafkaConsumerConfig.java
src/main/java/spot/spot/global/kafka/KafkaProducerConfig.java
src/main/java/spot/spot/global/mongodb/MongoDBConfig.java
src/main/resources/application-kafka.yml

kafka 프로파일 일 경우에 mongo, kafka 이용하도록 했습니다.

fix: mongo, kafka profile kafka일 경우 실행

---

src/main/resources/application-prod.yml
src/main/resources/application.yml

FIX: application.yml & application-prod.yml Hikari CP 배포 서버에 맞게 변경

---

src/main/java/spot/spot/domain/notification/command/service/FcmMessageUtil.java

FIX: 동시성 에러 잡기

---

src/main/resources/application.yml

톰켓스레드의 정상화
